ckpt_root: ckpt
cuda: True
num_workers: 8

dataset:
    name: 'CoughDataset'
    #common_kwargs:
        #image_size: (2048, 2048)
    train_kwargs:
        transform: 'train'
        txt: '/Users/xfwu/Documents/Stanford/CS230/covid19_cough_classification/lib/dataset/train.txt'   
    #valid_kwargs:
       # transform: 'valid'
       # txt: 'valid.txt'
    test_kwargs:
        transform: 'test'
        txt: '/Users/xfwu/Documents/Stanford/CS230/covid19_cough_classification/lib/dataset/test.txt'

training:
    optim: Adam
    epoch: 50
    batch_size: 20
    save_every: 5
    lr: 0.0001
    weight_decay: 0.0001

model:
    file: lib.model.resnet
    modelclass: ResNet
    loss_func: 'CrossEntropyLoss'


testing:
    batch_size: 1
    ckpt_root: 'ckpt'
